### PR TITLE
Fix sphinx start/stop/index commands for openshift

### PR DESCRIPTION
**Pull request by guicassolato**
**What this PR does / why we need it**:

`openshift:thinking_sphinx:start` rake task broke after we upgraded thinking_spinx from v3.2.0 to v3.4.2: https://github.com/3scale/porta/pull/1239/files#diff-33c867a743c81c1ce1e040ecbb221d39. The reason is because thinking_sphinx changed the API of `ThinkingSphinx::RakeInterface`: https://github.com/pat/thinking-sphinx/compare/v3.2.0...v3.4.2#diff-ec2634b6fd4c4a7faecb98d523a7026e

This is causing `system-sphinx` pod to loop crash on container initialization after throwing the following exception:

```
rake aborted!
NoMethodError: undefined method `stop' for #<ThinkingSphinx::RakeInterface:0x0000000008c12430>
/opt/system/lib/tasks/openshift.rake:40:in `block (3 levels) in <top (required)>'
/opt/system/vendor/bundle/ruby/2.4.0/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/opt/system/vendor/bundle/ruby/2.4.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/opt/rh/rh-ruby24/root/usr/local/bin/bundle:23:in `load'
/opt/rh/rh-ruby24/root/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => openshift:thinking_sphinx:start
(See full trace by running task with --trace)
```

### CODE REVIEW

**Comment by hallelujah** [comment]
Or just downgrade the gem
Lets not take any risk

**Comment by guicassolato** [comment]
We don't use this rake task to start sphinx in Saas, so no, it does not.
